name: build

on:
  push:
    branch:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install deps
        uses: py-actions/py-dependency-install@v2
      - name: Run tests
        run: python -m pytest

