name: build

on:
  push:
    branch:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup_python@v2
        with:
          python-version: '3.x'
      - name: Run tests
        run: pytest

